export default {
  CREATE: 'ACCOUNT__CREATE',
  EDIT: 'ACCOUNT__EDIT',
  DELETE: 'ACCOUNT__DELETE',
  STATUS: 'ACCOUNT__STATUS',
  IMPORT: 'ACCOUNT__IMPORT',
  RESEST_PASSWORD: 'ACCOUNT__RESEST_PASSWORD',
  SYNC_WORK_WX: 'ACCOUNT__SYNC_WORK_WX',
  SOCKET_TOKEN: 'ACCOUNT__SOCKET_TOKEN',
};
