export default {
  CREATE: 'DEPARTMENT__CREATE',
  EDIT: 'DEPARTMENT__EDIT',
  DELETE: 'DEPARTMENT__DELETE',
  SYNC_WORK_WX: 'DEPARTMENT__SYNC_WORK_WX',
  SOCKET_TOKEN: 'DEPARTMENT__SOCKET_TOKEN',
};
