export default {
  /**
   * 一、系统管理
   */
  SYSTEM: 'SYSTEM',
  // 部门管理
  DEPARTMENT: 'DEPARTMENT',
  // 角色管理
  ROLE: 'ROLE',
  // 账号管理
  SYSTEM_ACCOUNT: 'SYSTEM_ACCOUNT',
  // 模块管理
  SYSTEM_MODULES: 'SYSTEM_MODULES',
  // 系统日志
  SYSTEM_LOGS: 'SYSTEM_LOGS',
  // 消息中心
  MESSAGE_CENTER: 'MESSAGE_CENTER',
  // 温馨提示模板
  WARMPROMPT_TEMPLATE: 'WARMPROMPT_TEMPLATE',
  // 消息通知设置
  // NOTICE_SETTING: 'NOTICE_SETTING',

  /**
   * 二、组织管理
   */
  ORG: 'ORG',
  ORG_LIST: 'ORG_LIST',
  AGENT: 'AGENT',

  /**
   * 三、模板管理
   */
  TEMPLATE_MANAGEMENT: 'TEMPLATE_MANAGEMENT',
  ORGTEMPLATE_LIST: 'ORGTEMPLATE_LIST',
  // 药物管理
  MEDICATIONS_MANAGEMENT: 'MEDICATIONS_MANAGEMENT',
  MEDICATIONS_LIST: 'MEDICATIONS_LIST',
  MEDICATIONS_CATEGORIES: 'MEDICATIONS_CATEGORIES',
  MEDICATIONTAGS: 'MEDICATIONTAGS',
  // 素材管理
  MATERIAL_MANAGEMENT: 'MATERIAL_MANAGEMENT',
  MATERIAL_LIST: 'MATERIAL_LIST',
  MATERIAL_GROUP: 'MATERIAL_GROUP',
  // 饮食管理
  DIET_MANAGEMENT: 'DIET_MANAGEMENT',
  // 运动管理
  SPORT_MANAGEMENT: 'SPORT_MANAGEMENT',
  // 患者目标
  PATIENT_GOAL: 'PATIENT_GOAL',
  // 职业分类
  PROFESSION_MANAGEMENT: 'PROFESSION_MANAGEMENT',

  /**
   * 四、运营管理
   */
  COLLECTION: 'COLLECTION',
  COLLECTION_LIST: 'COLLECTION_LIST',
  SIGN_MANAGEMENT: 'SIGN_MANAGEMENT',
  /**
   * 五、工单管理
   */
  WORK: 'WORK',
  FLOW_LIST: 'FLOW_LIST',
  WORK_LIST: 'WORK_LIST',

  /**
   * 六、患者管理
   */
  PATIENTMANAGEMENT: 'PATIENTMANAGEMENT',
  // 患者列表
  PATIENT_LIST: 'PATIENT_LIST',
  // 患者记录
  PATIENTRECORDMENU: 'PATIENTRECORDMENU',
  SLEEP_RECORD: 'SLEEP_RECORD',
  MEDICATION_RECORD: 'MEDICATION_RECORD',
  MEDIA_RECORD: 'MEDIA_RECORD',
  MEDICAL_PROGRESS: 'MEDICAL_PROGRESS',
  DIET_RECORD: 'DIET_RECORD',
  SPORT_RECORD: 'SPORT_RECORD',
  QUESTIONNAIRE_RECORD: 'QUESTIONNAIRE_RECORD',
  // 标签管理
  // TAGS_MANAGEMENT: 'TAGS_MANAGEMENT',

  /** 七、量表管理 */
  // 量表管理
  QUESTIONNAIRE_MANAGEMENT: 'QUESTIONNAIRE_MANAGEMENT',
  QUESTIONNAIRE_LIST: 'QUESTIONNAIRE_LIST',
  QUESTIONNAIRE_CATEGORIES: 'QUESTIONNAIRE_CATEGORIES',
  QUESTION_LIBRARY: 'QUESTION_LIBRARY',
  QUESTION_CATEGORIES: 'QUESTION_CATEGORIES',

  /** 八、方案管理 */
  PROGRAM_MANAGEMENT: 'PROGRAM_MANAGEMENT',
  PROGRAM_LIST: 'PROGRAM_LIST',
  FEEDBACK_LIST: 'FEEDBACK_LIST',
  COMMITMENT_LIST: 'COMMITMENT_LIST',
};
