export default {
  VIEW_CONSOLE: 'MODULES__VIEW_CONSOLE',
  VIEW_ORGANIZATION: 'MODULES__VIEW_ORGANIZATION',
  NEW_CONSOLE: 'MODULES__NEW_CONSOLE',
  NEW_ORGANIZATION: 'MODULES__NEW_ORGANIZATION',
  EDIT_CONSOLE: 'MODULES__EDIT_CONSOLE',
  EDIT_ORGANIZATION: 'MODULES__EDIT_ORGANIZATION',
  DELETE_CONSOLE: 'MODULES__DELETE_CONSOLE',
  DELETE_ORGANIZATION: 'MODULES__DELETE_ORGANIZATION',
};
