export default {
  LIST: 'WORK_FORM__LIST',
  CREATE: 'WORK_FORM__CREATE',
  EDIT: 'WORK_FORM__EDIT',
  DELETE: 'WORK_FORM__DELETE',
  DETAIL: 'WORK_FORM__DETAIL',
  WORK_FLOWS: 'WORK_FORM__WORK_FLOWS',
  WX_USER: 'WORK_FORM__WX_USER',
  GENERATE_CODE: 'WORK_FORM__GENERATE_CODE',
};
