enum NoticeEnum {
  // // 睡眠处方
  CREATE_SLEEP_PRESCRIPTION = 'CREATE_SLEEP_PRESCRIPTION',
  // 系统通知
  SYSTEM_NOTICE = 'SYSTEM_NOTICE',
  SYSTEM_NOTICE_SUCCESS = 'SYSTEM_NOTICE_SUCCESS',
  SYSTEM_NOTICE_FAILED = 'SYSTEM_NOTICE_FAILED',
}
export default NoticeEnum;
